<?php
// Auto-generated by bin/update-build-info.sh - do not edit by hand.
define( 'APP_VERSION', '3.0.0' );
define( 'APP_BUILD', '7b97a0d' );
define( 'APP_BUILD_DATE', '2026-08-09 12:18:11 +0200' );
?>
