<?php
// Auto-generated by bin/update-build-info.sh - do not edit by hand.
define( 'APP_VERSION', '4.0.30' );
define( 'APP_BUILD', '8ffd05c' );
define( 'APP_BUILD_DATE', '2026-09-09 10:32:00 +0200' );
?>
