<?php
// Auto-generated by bin/update-build-info.sh - do not edit by hand.
define( 'APP_VERSION', '4.0.14' );
define( 'APP_BUILD', '0ffef23' );
define( 'APP_BUILD_DATE', '2026-09-05 22:13:21 +0200' );
?>
